(defun d-program ()
  (interactive)
  (erase-buffer)
  (insert "// a new D program")
  (newline)
  (insert "// author: sourav")
  (newline 2)
  (insert "import std.stdio;")
  (newline 2)
  (insert "void main()")
  (newline)
  (insert "{")
  (newline)
  (insert "writeln(\"hello, world!\");")
  (newline)
  (insert "}")
  (newline)
  (save-excursion
    (indent-region (point-min) (point-max) nil))
  (forward-line (- 2))
  (end-of-line))

